import jwt from 'jsonwebtoken';
import {
  Request, Response, NextFunction,
} from 'express';
import { PgColumn, PgTable } from 'drizzle-orm/pg-core';
import { InferSelectModel } from 'drizzle-orm';
import { transactions, investmentTypes, transactionTypes } from './resources/models/transactionModel';
import { categories } from './resources/models/categoryModel';
import { budgets, budgetTypes } from './resources/models/budgetModel';
import { goals } from './resources/models/goalModel';
import { monthlyBalances } from './resources/models/monthlyBalanceModel';
import { users } from './resources/models/userModel';
import { accounts, cards } from './resources/models/accountModel';

/* eslint-disable max-len, no-shadow, no-unused-vars, @typescript-eslint/no-unused-vars */

/** Base shape for any domain entity that is owned by a user. */
export type Content = { userId: number | undefined };

/** Authorization context stored in AsyncLocalStorage for the lifetime of a request. */
export type RequestContext = {
  userId: number;
  isAdmin: boolean;
};

/** A Drizzle table schema that is guaranteed to have a non-nullable userId column. */
export type TableWithUserId = Table & { userId: number };

/**
 * Interface for the Token
 */
export type Tokens = {
  /**
   * Access Token generated by the server
   */
  accessToken: string;
  /**
   * Refresh Token generated by the server
   */
  refreshToken: string;
};

/**
 * Interface for the Login Response
 */
export type LoginResponse = {
  /**
   * Access Token generated by the server
   */
  accessToken: string;
  /**
   * Refresh Token generated by the server
   */
  refreshToken: string;
  /**
   * User object
   */
  user: Omit<IUser, 'password' | 'createdAt' | 'updatedAt'>;
};

/**
 * Interface for the Token
 */
export interface Token extends jwt.Jwt {
  /**
   * Payload of the token. It contains the email, role, first name and last name
   */
  payload: {
    /** Email of the user */
    email: string;
    /** Role of the user. Can be either 'admin' or 'user' */
    role: 'admin' | 'user';
    /** First name of the user */
    firstName: string;
    /** Last name of the user */
    lastName: string;
  }
}

/**
 * Interface for the User Payload
 */
export type UserPayload = {
  /** Email of the user */
  email?: string;
  /** First name of the user */
  firstName?: string;
  /** Last name of the user */
  lastName?: string;
  /** Role of the user. Can be either 'admin' or 'user' */
  role?: 'admin' | 'user';
  /** Id of the user */
  id?: number;
};

export interface RequestWithUser extends Request {
  user?: UserPayload;
}

/**
 * Interface for token validation middleware
 */
export type TokenValidationMiddleware = (
  req: RequestWithUser,
  res: Response,
  next: NextFunction,
) => void;

export interface IContentController {
  /**
   * Create content.
   *
   * @param req - The request object
   * @param res - The response object
   * @returns The created content
   */
  createContent(req: RequestWithUser, res: Response): Promise<Response>;
  /**
   * Update content. If the user is an admin, they can update any content.
   *
   * @param req - The request object
   * @param res - The response object
   * @returns The updated content
   */
  updateContent(req: RequestWithUser, res: Response): Promise<Response>;
  /**
   * Delete content by id. If the user is an admin, they can delete any content.
   * If the user is not an admin, they can only delete their own content.
   *
   * @param req - The request object
   * @param res - The response object
   * @returns The deleted content
   */
  deleteContent(req: RequestWithUser, res: Response): Promise<Response>;
  /**
   * List user content. If the user is an admin, they can list all content.
   *
   * @param req - The request object
   * @param res - The response object
   * @returns The list of content
   */
  listContent(req: RequestWithUser, res: Response): Promise<Response>;
  /**
   * Get content by id. If the user is an admin, they can get any content.
   *
   * @param req - The request object
   * @param res - The response object
   * @returns The content
   */
  getContent(req: RequestWithUser, res: Response): Promise<Response>;
}

export interface IBudgetController extends IContentController {
  /**
   * Get budget by id. If the user is an admin, they can get any budget.
   *
   * @param req - The request object
   * @param res - The response object
   * @returns The budget
   */
  getBudget(req: RequestWithUser, res: Response): Promise<Response>;
}

/** All valid investment type values derived from the database enum. */
export const INVESTMENT_TYPES = investmentTypes.enumValues;
/** All valid transaction type values derived from the database enum. */
export const TRANSACTION_TYPES = transactionTypes.enumValues;
/** All valid budget type values derived from the database enum. */
export const BUDGET_TYPES = budgetTypes.enumValues;

/** A goal with its display name and the percentage allocated to it. */
export interface IGoalItem {
  /** The full goal record. */
  goal: IGoal;
  /** Human-readable name of the goal. */
  goalName: string;
  /** Fraction of the transaction amount directed to this goal (0–1). */
  percentage: number;
}

/** Domain entity representing a payment card. */
export interface ICard extends InferSelectModel<typeof cards> { }

/** Card fields accepted from account create/update forms. */
export type ICardPayload = Pick<ICard, 'number' | 'expirationDate' | 'closingDay'>;

/** Card payload used when reconciling a submitted full account card list. */
export type ICardSyncPayload = ICardPayload & {
  /** Existing card id. Omitted for newly added cards. */
  id?: number;
};

/** Card brands rendered by the client card components. */
export type ICardBrand = 'amazon' | 'master' | 'visa' | 'amex' | 'diners' | 'discover' | 'maestro' | 'unknown';

/** Card payload returned to the client when accounts are hydrated with their cards. */
export type ICardClientPayload = ICardSyncPayload & {
  /** Client-rendered card brand/flag. */
  flag: ICardBrand;
  /** Last four digits rendered by the client card component. */
  last4Digits: string;
};

/** Domain entity representing a bank or financial account. */
export interface IAccount extends InferSelectModel<typeof accounts> { }

/** Account row loaded with its related persisted cards. */
export type IAccountWithCards = IAccount & {
  /** Cards related to the account by Drizzle relations. */
  cards: ICard[];
};

/** Account create/update payload that may include the UI-submitted full card list. */
export type IAccountPayload = Partial<IAccount> & Content & {
  /** Full list of cards submitted by the account form. */
  cards?: Array<ICardSyncPayload | ICardClientPayload>;
};

/** Domain entity representing an application user. */
export interface IUser extends InferSelectModel<typeof users> { }

/** Domain entity representing a financial transaction. */
export interface ITransaction extends InferSelectModel<typeof transactions> { }

/** Transaction enriched with its related account name and category name. */
export type ITransactionWithRelations = ITransaction & {
  accountName: string;
  categoryName: string | null;
};

/** Domain entity representing a savings goal. */
export interface IGoal extends InferSelectModel<typeof goals> { }

/** Domain entity representing a spending category. */
export interface ICategory extends InferSelectModel<typeof categories> { }

/** Domain entity representing a budget with its computed total spent amount. */
export interface IBudget extends InferSelectModel<typeof budgets> {
  /** Total amount spent against this budget in the relevant period. */
  spent?: number;
  /** Category rows hydrated for list/detail responses. */
  categories?: ICategory[];
  /** Category ids submitted by create/update requests. */
  categoryIds?: number[];
}

/** Domain entity representing a monthly balance snapshot for an account. */
export interface IMonthlyBalance extends InferSelectModel<typeof monthlyBalances> { }

/** Payload used to bulk-update a goal's saved value by a fixed amount. */
export type BulkGoalsUpdate = {
  /** The id of the goal to update. */
  goalId: number;
  /** The absolute amount to add or subtract from the goal's saved value. */
  amount: number;
};

/** A single goal allocation entry within a transaction, defined by fraction. */
export type ITransactionGoalEntry = {
  /** The id of the goal receiving this allocation. */
  goalId: number;
  /** Fraction of the transaction amount directed to this goal (0–1). */
  percentage: number;
};

/**
 * Minimal shape every Drizzle table must satisfy to be usable with
 * {@link Repository} and {@link getAutorizationDatabaseContext}.
 */
export interface Table extends PgTable {
  /** Primary key column. */
  id: PgColumn;
  /** Optional user ownership column used for authorization filtering. */
  userId?: PgColumn;
}

/**
 * Generic CRUD contract shared by all repository implementations.
 *
 * @template T - The Drizzle table type.
 * @template K - The domain entity type.
 */
export interface IRepository<T extends Table, K> {
  /** Human-readable model name used in log messages and error strings. */
  modelName: string;
  /**
   * Finds a record by primary key within the current authorization context.
   *
   * @param id - The primary key to look up.
   * @returns The matching record, or null if not found.
   */
  findById(id: number): Promise<K | null>;
  /**
   * Inserts a new record and returns the persisted row.
   *
   * @param entity - The entity data to insert.
   * @returns The newly inserted row.
   */
  save(entity: Partial<K>): Promise<K>;
  /**
   * Deletes the record identified by id and returns the deleted row.
   *
   * @param id - The primary key of the record to delete.
   * @returns The deleted row, or null if not found.
   */
  deleteById(id: number): Promise<K | null>;
  /**
   * Returns all records visible to the current authorization context.
   *
   * @returns An array of all matching records.
   */
  listAll(): Promise<K[]>;
  /**
   * Applies a partial update to the record identified by id.
   *
   * @param id - The primary key of the record to update.
   * @param entity - Partial fields to apply.
   * @returns The updated row.
   */
  update(id: number, entity: Partial<K>): Promise<K>;
}

/** Repository contract for the transactions table, extending base CRUD with domain-specific queries. */
export interface ITransactionRepo extends IRepository<typeof transactions, ITransaction> {
  /**
   * Returns the count of transaction-goal links for a goal, scoped to the authorization context.
   *
   * @param goalId - The goal to check.
   * @returns Count of linked transaction rows.
   */
  deleteGoalFromTransactions(goalId: number): Promise<number>;
  /**
   * Sets categoryId to null on all transactions belonging to the given categories.
   *
   * @param categoryIds - The category ids to disassociate.
   * @returns Number of transactions updated.
   */
  removeCategoriesFromTransactions(categoryIds: number[]): Promise<number>;
  /**
   * Finds transactions for a user filtered by category ids and date range.
   *
   * @param userId - The owning user's id.
   * @param categoryIds - Category ids to match.
   * @param startDate - Range start (inclusive).
   * @param endDate - Range end (inclusive).
   * @returns Matching transactions.
   */
  findByCategoryWithDateRange(
    userId: number,
    categoryIds: number[],
    startDate: Date,
    endDate: Date,
  ): Promise<ITransaction[]>;
  /**
   * Finds all transactions for a given year and month without authorization filtering.
   *
   * @param year - The four-digit year.
   * @param month - The month (1-indexed).
   * @returns Matching transactions.
   */
  findByMonthAndYear(year: number, month: number): Promise<ITransaction[]>;
  /**
   * Removes all goal junction rows for the given transaction.
   *
   * @param transactionId - The transaction whose goal links should be removed.
   * @returns Number of rows deleted.
   */
  deleteTransactionFromGoals(transactionId: number): Promise<number>;
  /**
   * Inserts goal allocation rows linking a transaction to a set of goals.
   *
   * @param transactionId - The transaction to link.
   * @param goals - The goal entries with goalId and percentage.
   */
  saveTransactionGoals(transactionId: number, goals: ITransactionGoalEntry[]): Promise<void>;
  /**
   * Lists all transactions for the current authorization context, joined with
   * their related account name and category name.
   *
   * @returns Transactions enriched with `accountName` and `categoryName`.
   */
  listAllWithRelations(): Promise<ITransactionWithRelations[]>;
}

/** Repository contract for the categories table, extending base CRUD with hierarchy queries. */
export interface ICategoryRepo extends IRepository<typeof categories, ICategory> {
  /**
   * Returns all categories whose parent is the given category id.
   *
   * @param parentCategoryId - The parent category to query under.
   * @returns All direct child categories.
   */
  findAllSubcategories(parentCategoryId: number): Promise<ICategory[]>;
  /**
   * Deletes all subcategories of the given parent category.
   *
   * @param parentCategoryId - The parent whose children should be deleted.
   * @returns Number of rows deleted, or null if none matched.
   */
  deleteAllSubcategories(parentCategoryId: number): Promise<number | null>;
  /**
   * Returns the category ids associated with a given budget.
   *
   * @param budgetId - The budget to look up categories for.
   * @returns An array of category ids.
   */
  listCategoriesByBudgetId(budgetId: number): Promise<number[]>;
}

/** Repository contract for the goals table, extending base CRUD with transaction-driven updates. */
export interface IGoalRepo extends IRepository<typeof goals, IGoal> {
  /**
   * Updates the savedValue of all goals linked to the transaction by their percentage.
   *
   * @param transaction - The transaction whose linked goals should be updated.
   * @param shouldInvertValue - When true the contribution is subtracted (used on delete/revert).
   */
  updateGoalFromTransaction(transaction: ITransaction, shouldInvertValue?: boolean): Promise<void>;
  /**
   * Lists goals with savedValue computed from transactions up to the last day of the given month.
   *
   * @param year - The four-digit year.
   * @param month - The month, 1-indexed.
   * @returns Goals with a month-scoped savedValue.
   */
  listGoalsWithSavedValueUpTo(year: number, month: number): Promise<IGoal[]>;
}

/** Repository contract for the budgets table, extending base CRUD with usage tracking. */
export interface IBudgetRepo extends IRepository<typeof budgets, IBudget> {
  /**
   * Inserts a budgetUsage row for every budget whose categories include the transaction's category.
   *
   * @param transaction - The newly created transaction to record.
   */
  updateBudgetsByNewTransaction(transaction: ITransaction): Promise<void>;
  /**
   * Removes the budgetUsage row associated with the given transaction.
   *
   * @param transaction - The transaction whose usage entry should be deleted.
   */
  revertBudgetsByTransaction(transaction: ITransaction): Promise<void>;
  /**
   * Creates budget/category junction rows for a persisted budget.
   *
   * @param budgetId - The persisted budget id.
   * @param categoryIds - Category ids linked to the budget.
   */
  saveBudgetCategories(budgetId: number, categoryIds: number[]): Promise<void>;
  /**
   * Deletes budget/category junction rows for a persisted budget.
   *
   * @param budgetId - The persisted budget id.
   */
  deleteBudgetCategories(budgetId: number): Promise<void>;
  listBudgetsWithCategories(): Promise<IBudget[]>;
  /**
   * Lists all budgets with categories and their total spent amount from budgetUsage.
   *
   * @returns Budgets with categories and a computed `spent` field.
   */
  listBudgetsWithSpent(): Promise<IBudget[]>;
}

/** Repository contract for the monthlyBalances table, extending base CRUD with balance management. */
export interface IMonthlyBalanceRepo extends IRepository<typeof monthlyBalances, IMonthlyBalance> {
  /**
   * Finds the monthly balance for the transaction's account on the given date's month.
   *
   * @param transaction - Used to match the accountId.
   * @param date - The date whose year and month identify the balance record.
   * @returns The monthly balance, or null if none exists.
   */
  findMonthlyBalance(transaction: ITransaction, date: Date): Promise<IMonthlyBalance | null>;
  /**
   * Atomically updates closingBalance, totalIn, and totalOut for the transaction's account month.
   *
   * @param transaction - The transaction to apply or revert.
   * @param shouldInvertValue - When true the transaction's impact is subtracted.
   */
  updateMonthlyBalanceWithTransaction(transaction: ITransaction, shouldInvertValue: boolean): Promise<void>;
  /**
   * Returns all monthly balance records for a given year and month,
   * scoped to the current authorization context.
   *
   * @param year - The four-digit year.
   * @param month - The month (1-indexed).
   */
  findByYearAndMonth(year: number, month: number): Promise<IMonthlyBalance[]>;
}

/** Repository contract for the users table, extending base CRUD with email lookup. */
export interface IUserRepo extends IRepository<typeof users, IUser> {
  /**
   * Finds a user by their email address.
   *
   * @param email - The email address to search for.
   * @returns The matching user, or null if not found.
   */
  findByEmail(email: string): Promise<IUser | null>;
}

/** Repository contract for the accounts table. */
export interface IAccountRepo extends IRepository<typeof accounts, IAccount> {
  /**
   * Returns all visible accounts with their related cards loaded by Drizzle relations.
   *
   * @returns Accounts with persisted cards included.
   */
  listAllWithCards(): Promise<IAccountWithCards[]>;
}

/** Repository contract for account-owned payment cards. */
export interface ICardRepo extends IRepository<typeof cards, ICard> {
  /**
   * Finds all cards that belong to the given account.
   *
   * @param accountId - The owner account id.
   * @returns Cards belonging to the account.
   */
  findByAccountId(accountId: number): Promise<ICard[]>;
  /**
   * Reconciles the persisted cards for an account with a submitted full list.
   *
   * @param accountId - The owner account id.
   * @param submittedCards - The full card list submitted by the UI.
   * @returns The reconciled persisted cards.
   */
  syncAccountCards(accountId: number, submittedCards: ICardSyncPayload[]): Promise<ICard[]>;
}

/** Callback invoked when a controller catches an unhandled error. */
export type ErrorHandler = (error: Error) => void;

/**
 * Optional route handler overrides passed to a router factory.
 * Any provided handler replaces the default implementation for that route.
 */
export type RouteOverrides = {
  listContent?: (req: RequestWithUser, res: Response) => Promise<Response>;
  createContent?: (req: RequestWithUser, res: Response) => Promise<Response>;
  getContent?: (req: RequestWithUser, res: Response) => Promise<Response>;
  updateContent?: (req: RequestWithUser, res: Response) => Promise<Response>;
  deleteContent?: (req: RequestWithUser, res: Response) => Promise<Response>;
};

export interface IAccountantManager {
  createTransaction: (content: ITransaction, goals?: ITransactionGoalEntry[]) => Promise<ITransaction>;
  deleteTransaction: (id: number) => Promise<ITransaction | null>;
  updateTransaction: (
    id: number,
    payload: Partial<ITransaction>,
    goals: ITransactionGoalEntry[] | undefined,
  ) => Promise<ITransaction | null>;
  getTransaction: (id: number) => Promise<ITransaction | null>;
  listTransactions: () => Promise<ITransactionWithRelations[]>;
  listMonthlyBalances: (year: number, month: number) => Promise<IMonthlyBalance[]>;
  getTransactionTypes: () => { transactionTypes: string[]; investmentTypes: string[] };
}

export interface ICommonController<T extends Content> {
  /**
     * Creates a new content.
     *
     * @throws {Error} - If no user is parsed in the request.
     * @throws {Error} - If the payload is void.
     *
     * @param req - The request object.
     * @param res - The response object.
     * @returns The created content.
     */
  createContent: (req: RequestWithUser, res: Response) => Promise<Response<T>>;
  /**
   * Updates a content.
   *
   * @throws {Error} - If no user is parsed in the request.
   * @throws {Error} - If the payload is void.
   * @throws {Error} - If the content is not found.
   * @throws {Error} - If the user is not authorized to update the content.
   *
   * @param req - The request object.
   * @param res - The response object.
   * @returns The updated content.
   */
  updateContent: (req: RequestWithUser, res: Response) => Promise<Response<T>>;
  /**
   * Deletes a content by id.
   *
   * @throws {Error} - If no user is parsed in the request.
   * @throws {Error} - If the content is not found.
   * @throws {Error} - If the user is not authorized to delete the content.
   * @throws {Error} - If the content id is not found in the request parameters.
   *
   * @param req - The request object.
   * @param res - The response object.
   * @returns The deleted content.
   */
  deleteContent: (req: RequestWithUser, res: Response) => Promise<Response<T>>;
  /**
   * Lists all content for a user.
   *
   * @throws {Error} - If no user is parsed in the request.
   *
   * @param req - The request object.
   * @param res - The response object.
   * @returns The list of content.
   */
  listContent: (req: RequestWithUser, res: Response) => Promise<Response<T>>;
  /**
   * Gets a content by id.
   *
   * @throws {Error} - If no user is parsed in the request.
   * @throws {Error} - If the content is not found.
   * @throws {Error} - If the content id is not found in the request parameters.
   *
   * @param req - The request object.
   * @param res - The response object.
   * @returns The content.
   */
  getContent: (req: RequestWithUser, res: Response) => Promise<Response<T>>;
}

export interface ICommonActions<K extends Content> {
  /**
   * Creates a new content.
   *
   * @throws {Error} - If the payload is void.
   *
   * @param content - The content to create.
   * @returns The created content.
   */
  createContent: (content: K) => Promise<K>;
  /**
   * Updates a content.
   *
   * @throws {Error} - If the payload is void.
   * @throws {Error} - If the content is not found.
   * @throws {Error} - If the user is not authorized to update the content.
   *
   * @param id - The id of the content to update.
   * @param payload - The payload to update the content with.
   * @returns The updated content.
   */
  updateContent: (
    id: number,
    payload: Partial<K>,
  ) => Promise<K | null>;
  /**
   * Deletes a content by id.
   *
   * @throws {Error} - If the content is not found.
   * @throws {Error} - If the user is not authorized to delete the content.
   *
   * @param id - The id of the content to delete.
   * @returns The deleted content.
   */
  deleteContent: (id: number) => Promise<K | null>;
  /**
   * Lists all content for a user.
   *
   * @throws {Error} - If the user is not authorized to list the content.
   *
   * @returns The list of content.
   */
  listContent: () => Promise<K[]>;
  /**
   * Gets a content by id.
   *
   * @throws {Error} - If the content is not found.
   * @throws {Error} - If the user is not authorized to get the content.
   *
   * @param id - The id of the content to get.
   * @returns The content.
   */
  getContent: (id: number) => Promise<K | null>;
}

export interface IGoalActions extends ICommonActions<IGoal> {
  listGoalsForMonth(year: number, month: number): Promise<IGoal[]>;
}

/**
 * Aggregated manager actions passed to the budget page controller,
 * covering the four content types that a budget view can interact with.
 */
export type ContentManagerActions = {
  /** CRUD actions for budgets. */
  budgetActions: ICommonActions<IBudget>;
  /** CRUD actions for categories. */
  categoryActions: ICommonActions<ICategory>;
  /** CRUD actions for goals. */
  goalActions: IGoalActions;
  /** CRUD actions for accounts. */
  accountActions: ICommonActions<IAccountPayload>;
};

/* eslint-enable no-unused-vars */
