version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: financas-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    command: ["--noauth"]

volumes:
  mongo-data:
