export enum BankAccountActionType {
  SET_NAME = 'SET_NAME',
  SET_CURRENCY = 'SET_CURRENCY',
  SET_ACCOUNT_NUMBER = 'SET_ACCOUNT_NUMBER',
  SET_AGENCY = 'SET_AGENCY',
  VALIDATE = 'VALIDATE',
}

export enum ChangePasswordActionType {
  SET_PROPERTY = 'SET_PROPERTY',
  SET_NEW_PASSWORD_ERROR = 'SET_NEW_PASSWORD_ERROR',
  SET_CONFIRM_PASSWORD_ERROR = 'SET_CONFIRM_PASSWORD_ERROR',
}

export enum CreditCardActionType {
  SET_NUMBER = 'SET_NUMBER',
  SET_EXPIRATION_DATE = 'SET_EXPIRATION_DATE',
  VALIDATE = 'VALIDATE',
  RESET = 'RESET',
}

export enum SettingsActionType {
  SET_FIRST_NAME_ERROR = 'SET_FIRST_NAME_ERROR',
  SET_LAST_NAME_ERROR = 'SET_LAST_NAME_ERROR',
  SET_PROPERTY = 'SET_PROPERTY',
  SET_IS_DIRTY = 'SET_IS_DIRTY',
  RESET_STATE = 'RESET_STATE',
}

export enum GoalActionType {
  SET_NAME = 'SET_NAME',
  SET_VALUE = 'SET_VALUE',
  SET_DUE_DATE = 'SET_DUE_DATE',
  VALIDATE = 'VALIDATE',
  RESET = 'RESET',
}

export enum GoalsTableActionType {
  EDIT = 'edit',
  DELETE = 'delete',
  ARCHIVE = 'archive',
  UNARCHIVE = 'unarchive',
}
