name: Update Badges

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'README.md'

jobs:
  update-badges:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm ci

      - name: Install lcov-summary
        run: npm install -g lcov-summary

      - name: Run server tests with coverage
        run: npm run test:server

      - name: Run client tests with coverage
        run: npm run test:client

      - name: Update Badges
        run: |
          # Update version badge
          PROJECT_VERSION=$(node -pe "require('./package.json').version")
          VERSION_BADGE_URL="https://img.shields.io/badge/version-$PROJECT_VERSION-brightgreen.svg"
          
          # Get server coverage
          SERVER_COVERAGE=$(lcov-summary coverage/lcov.info | grep "Total Coverage:" | awk '{print $3}' | tr -d '%')
          
          # Get client coverage
          CLIENT_COVERAGE=$(cat client-cov/coverage-summary.json | jq -r '.total.lines.pct')
          
          # Determine badge colors
          SERVER_COLOR=$([ $(echo "$SERVER_COVERAGE >= 80" | bc -l) -eq 1 ] && echo "brightgreen" || echo "red")
          CLIENT_COLOR=$([ $(echo "$CLIENT_COVERAGE >= 80" | bc -l) -eq 1 ] && echo "brightgreen" || echo "red")
          
          # Create badge URLs
          SERVER_BADGE_URL="https://img.shields.io/badge/server--coverage-$SERVER_COVERAGE%25-$SERVER_COLOR"
          CLIENT_BADGE_URL="https://img.shields.io/badge/client--coverage-$CLIENT_COVERAGE%25-$CLIENT_COLOR"
          
          # Update README badges
          sed -i "s|!\[Version\].*|![Version]($VERSION_BADGE_URL)|" README.md
          sed -i "s|!\[Server Coverage\].*|![Server Coverage]($SERVER_BADGE_URL)|" README.md
          sed -i "s|!\[Client Coverage\].*|![Client Coverage]($CLIENT_BADGE_URL)|" README.md

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "docs: Update badges"
          title: "docs: Update badges"
          body: "Update version and coverage badges"
          branch: "chore/update-badges"
          base: "master"
          delete-branch: true
